### ISSUE TITLE
Use gRPC Client to Interact with generateApiKey API

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/elastos-nucleus#19]

**Comment by Ashwin-Pokharel** [comment]
![Screen Shot 2019-11-19 at 9 37 14 AM](https://user-images.githubusercontent.com/50914916/69155741-46688c00-0ab0-11ea-9b16-bd426abc2075.png)

This is error that I get when trying to start up a grpc server.

**Comment by kpachhai** [comment]
Please open this issue on Elastos smartweb service GitHub repo not nuclues repo as this doesn't relate to nucleus project at all.

**Comment by kpachhai** [comment]
We talked about this issue yesterday at the meeting. @rahulguna  and  @prasadpgowda  should put up a fix soon I think.
